blank_issues_enabled: false
contact_links:
  - name:   
    url: https://github.com/AnLoMinus/FixCry/discussions
    about: 砖转 转, 爪注转 砖驻专  注 驻专拽
  - name:  转注 注专
    url: https://github.com/AnLoMinus/FixCry/wiki
    about: 专, 转注  注专 砖转砖
  - name:   注 注转 
    url: https://github.com/AnLoMinus/FixCry/security/advisories/new
    about:  注 注转  专砖转
